"""Python reference implementation of Determa State format 1."""

from __future__ import annotations

import logging

from .__about__ import __version__
from .checkpoint import (
    RestoredExecutionCheckpoint,
    execution_checkpoint_digest,
    restore_execution_checkpoint,
    seal_execution_checkpoint,
    serialize_execution_checkpoint,
    validate_execution_checkpoint_member,
    validate_execution_checkpoint_semantics,
)
from .definition import Bundle, BundleSource, load_bundle
from .engine import Delivery, Result, create, dispatch
from .errors import (
    ArtifactError,
    CelError,
    DetermaError,
    ErrorRecord,
    SchemaError,
    ValidationError,
)
from .host import (
    ExecutionHost,
    ExecutionHostError,
    SharedExecutionTransaction,
    StagedExecutionResult,
    creation_request_digest,
    delivery_request_digest,
    maintenance_migration_request_digest,
    outbox_intent_digest,
    portable_envelope,
    validate_host_profile,
)
from .migration import (
    MigrationDispatchResult,
    MigrationFailure,
    MigrationLimits,
    MigrationResult,
    migrate_aggregate,
    migrate_and_dispatch,
)
from .stores import (
    COMPACT_EFFECT_IDENTITY_RETENTION,
    DURABLE_CONCURRENT,
    DURABLE_SINGLE_WRITER,
    EPHEMERAL,
    PERMANENT_OUTBOX_TERMINAL_RETENTION,
    PERMANENT_RECEIPT_RETENTION,
    RESTART_PERSISTENT,
    ROOT_IDENTITY_RETENTION,
    SHARED_APPLICATION_TRANSACTION,
    STANDARD_CAPABILITIES,
    ExecutionStore,
    ExecutionStoreError,
    ExecutionStoreFactory,
    ExecutionStoreRegistry,
    ExecutionStoreTransaction,
    FileExecutionStore,
    MemoryExecutionStore,
    PostgreSQLExecutionStore,
    SQLiteExecutionStore,
    bundled_execution_store_registry,
    file_execution_store_factory,
    memory_execution_store_factory,
    postgresql_execution_store_factory,
    register_bundled_execution_stores,
    sqlite_execution_store_factory,
)
from .validator import collect_errors, validate
from .wire import (
    ArtifactResolver,
    DefinitionResolver,
    MemoryArtifactResolver,
    MigrationDescriptorResolver,
    RestoredAggregate,
    RestoredAggregatePackage,
    aggregate_envelope,
    aggregate_shape_fingerprint,
    restore_aggregate,
    restore_aggregate_package,
    serialize_aggregate,
)

__all__ = [
    "ArtifactError",
    "ArtifactResolver",
    "Bundle",
    "BundleSource",
    "CelError",
    "COMPACT_EFFECT_IDENTITY_RETENTION",
    "DURABLE_CONCURRENT",
    "DURABLE_SINGLE_WRITER",
    "DetermaError",
    "DefinitionResolver",
    "Delivery",
    "ErrorRecord",
    "EPHEMERAL",
    "ExecutionHost",
    "ExecutionHostError",
    "ExecutionStore",
    "ExecutionStoreError",
    "ExecutionStoreFactory",
    "ExecutionStoreRegistry",
    "ExecutionStoreTransaction",
    "FileExecutionStore",
    "MemoryArtifactResolver",
    "MemoryExecutionStore",
    "MigrationDescriptorResolver",
    "MigrationDispatchResult",
    "MigrationFailure",
    "MigrationLimits",
    "MigrationResult",
    "PERMANENT_OUTBOX_TERMINAL_RETENTION",
    "PERMANENT_RECEIPT_RETENTION",
    "PostgreSQLExecutionStore",
    "RESTART_PERSISTENT",
    "ROOT_IDENTITY_RETENTION",
    "Result",
    "RestoredAggregate",
    "RestoredAggregatePackage",
    "RestoredExecutionCheckpoint",
    "SHARED_APPLICATION_TRANSACTION",
    "STANDARD_CAPABILITIES",
    "SchemaError",
    "SharedExecutionTransaction",
    "SQLiteExecutionStore",
    "StagedExecutionResult",
    "ValidationError",
    "__version__",
    "aggregate_envelope",
    "aggregate_shape_fingerprint",
    "collect_errors",
    "create",
    "creation_request_digest",
    "bundled_execution_store_registry",
    "delivery_request_digest",
    "dispatch",
    "execution_checkpoint_digest",
    "file_execution_store_factory",
    "load_bundle",
    "migrate_aggregate",
    "migrate_and_dispatch",
    "memory_execution_store_factory",
    "maintenance_migration_request_digest",
    "outbox_intent_digest",
    "portable_envelope",
    "postgresql_execution_store_factory",
    "register_bundled_execution_stores",
    "restore_aggregate",
    "restore_aggregate_package",
    "restore_execution_checkpoint",
    "seal_execution_checkpoint",
    "serialize_aggregate",
    "serialize_execution_checkpoint",
    "sqlite_execution_store_factory",
    "validate",
    "validate_execution_checkpoint_member",
    "validate_execution_checkpoint_semantics",
    "validate_host_profile",
]

logging.getLogger("determa.state").addHandler(logging.NullHandler())
