"""Python reference implementation of Determa State format 1."""

from __future__ import annotations

import logging

from .__about__ import __version__
from .checkpoint import (
    execution_checkpoint_digest,
    seal_execution_checkpoint,
    serialize_execution_checkpoint,
    validate_execution_checkpoint_member,
)
from .checkpoint_v2 import (
    RestoredExecutionCheckpoint,
    admit_checkpoint_v2,
    create_checkpoint_v2,
    process_delivery_checkpoint_v2,
    prune_checkpoint_v2,
    restore_execution_checkpoint_v2,
    step_checkpoint_v2,
)
from .codes import (
    PORTABLE_CODE_SETS,
    CheckpointArtifactFailureCode,
    CheckpointHostFailureCode,
    CheckpointPreAcceptanceFailureCode,
    CreationRejectionCode,
    DispatchRejectionCode,
    DispositionCode,
    EngineFaultCode,
    ExecutionStoreAdapterFailureCode,
    MachineLoadFailureCode,
    PersistenceFailureCode,
)
from .definition import Bundle, BundleSource, load_bundle
from .errors import (
    ArtifactError,
    CelError,
    DetermaError,
    ErrorRecord,
    SchemaError,
    ValidationError,
)
from .host import (
    ExecutionHost,
    ExecutionHostError,
    SharedExecutionTransaction,
    StagedExecutionResult,
    creation_request_digest,
    delivery_request_digest,
    maintenance_migration_request_digest,
    outbox_intent_digest,
    portable_envelope,
    validate_host_profile,
)
from .migration import (
    MigrationLimits,
    restore_migration_descriptor_v2,
)
from .persistence import (
    DurableHostStore,
    MemoryDurableHostStore,
    PersistenceHost,
    SQLiteDurableHostStore,
)
from .queueing import (
    admit_aggregate_v2 as admit,
)
from .queueing import (
    create_aggregate_v2 as create,
)
from .queueing import (
    migrate_aggregate_v2,
    restore_aggregate_v2,
    seal_aggregate_v2,
)
from .queueing import (
    step_aggregate_v2 as step,
)
from .stores import (
    COMPACT_EFFECT_IDENTITY_RETENTION,
    DURABLE_CONCURRENT,
    DURABLE_SINGLE_WRITER,
    EPHEMERAL,
    PERMANENT_OUTBOX_TERMINAL_RETENTION,
    PERMANENT_RECEIPT_RETENTION,
    RESTART_PERSISTENT,
    ROOT_IDENTITY_RETENTION,
    SHARED_APPLICATION_TRANSACTION,
    STANDARD_CAPABILITIES,
    ExecutionStore,
    ExecutionStoreError,
    ExecutionStoreFactory,
    ExecutionStoreRegistry,
    ExecutionStoreTransaction,
    FileExecutionStore,
    MemoryExecutionStore,
    PostgreSQLExecutionStore,
    SQLiteExecutionStore,
    bundled_execution_store_registry,
    file_execution_store_factory,
    memory_execution_store_factory,
    postgresql_execution_store_factory,
    register_bundled_execution_stores,
    sqlite_execution_store_factory,
)
from .validator import collect_errors, validate
from .wire import (
    ArtifactResolver,
    DefinitionResolver,
    MemoryArtifactResolver,
    MigrationDescriptorResolver,
    RestoredAggregate,
    RestoredAggregatePackage,
    aggregate_envelope,
    aggregate_shape_fingerprint,
    restore_aggregate,
    restore_aggregate_package,
    serialize_aggregate,
)

__all__ = [
    "ArtifactError",
    "ArtifactResolver",
    "admit",
    "admit_checkpoint_v2",
    "Bundle",
    "BundleSource",
    "CelError",
    "CheckpointArtifactFailureCode",
    "CheckpointHostFailureCode",
    "CheckpointPreAcceptanceFailureCode",
    "COMPACT_EFFECT_IDENTITY_RETENTION",
    "DURABLE_CONCURRENT",
    "DURABLE_SINGLE_WRITER",
    "DurableHostStore",
    "DetermaError",
    "DefinitionResolver",
    "CreationRejectionCode",
    "create_checkpoint_v2",
    "DispatchRejectionCode",
    "DispositionCode",
    "ErrorRecord",
    "EPHEMERAL",
    "EngineFaultCode",
    "ExecutionHost",
    "ExecutionHostError",
    "ExecutionStore",
    "ExecutionStoreError",
    "ExecutionStoreFactory",
    "ExecutionStoreRegistry",
    "ExecutionStoreTransaction",
    "ExecutionStoreAdapterFailureCode",
    "FileExecutionStore",
    "MemoryArtifactResolver",
    "MemoryDurableHostStore",
    "MemoryExecutionStore",
    "MachineLoadFailureCode",
    "MigrationDescriptorResolver",
    "MigrationLimits",
    "migrate_aggregate_v2",
    "PERMANENT_OUTBOX_TERMINAL_RETENTION",
    "PERMANENT_RECEIPT_RETENTION",
    "PostgreSQLExecutionStore",
    "PORTABLE_CODE_SETS",
    "PersistenceFailureCode",
    "PersistenceHost",
    "RESTART_PERSISTENT",
    "ROOT_IDENTITY_RETENTION",
    "RestoredAggregate",
    "RestoredAggregatePackage",
    "RestoredExecutionCheckpoint",
    "SHARED_APPLICATION_TRANSACTION",
    "STANDARD_CAPABILITIES",
    "SchemaError",
    "SharedExecutionTransaction",
    "SQLiteExecutionStore",
    "SQLiteDurableHostStore",
    "StagedExecutionResult",
    "ValidationError",
    "__version__",
    "aggregate_envelope",
    "aggregate_shape_fingerprint",
    "collect_errors",
    "create",
    "creation_request_digest",
    "bundled_execution_store_registry",
    "delivery_request_digest",
    "execution_checkpoint_digest",
    "file_execution_store_factory",
    "load_bundle",
    "memory_execution_store_factory",
    "maintenance_migration_request_digest",
    "outbox_intent_digest",
    "portable_envelope",
    "postgresql_execution_store_factory",
    "prune_checkpoint_v2",
    "process_delivery_checkpoint_v2",
    "register_bundled_execution_stores",
    "restore_aggregate",
    "restore_aggregate_v2",
    "restore_aggregate_package",
    "restore_execution_checkpoint_v2",
    "restore_migration_descriptor_v2",
    "seal_aggregate_v2",
    "seal_execution_checkpoint",
    "serialize_aggregate",
    "serialize_execution_checkpoint",
    "step",
    "step_checkpoint_v2",
    "sqlite_execution_store_factory",
    "validate",
    "validate_execution_checkpoint_member",
    "validate_host_profile",
]

logging.getLogger("determa.state").addHandler(logging.NullHandler())
